### ISSUE TITLE
Expand WebSocket subscription system

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox-store-blob#17]
Precursor to #13 and second part of #16.

I asked during the call whether data pulled through polling and data pushed live through WS should be controlled by different permissions, and the consensus was that yes they should.

In order to be consistent with how tokens are passed in other places (and also to give app devs less to learn) I think we should extend how WS streaming works.

Firstly, that streaming data (in or out via WS) should be separated from subscribing to data, and the authorization that will need to entail.

Secondly, that subscription should be by endpoint, which the store will understand to mean sensor or key. Since we already have authorization for paths, this would kill two birds with one stone (similar to #15).

I propose that for every item pushed to a store-hosted Hypercat catalogue, there should be an equivalent WS subscription endpoint. How this works exactly is not that important — we could have both as items in the catalogue automatically, or we could say that the driver has to push them to the catalogue (and thus control what data can be subscribed to at all), or we could have a metadata flag for things that are subscribable via WS.

For example, for the endpoint:

    /api/key/:key

we have the subscription endpoint similar to anything like:

    /subscribe/api/key/:key
    /subscribe/key/:key
    /subscribe/api/key/:key
    /sub/key/:key

We could decide on anything for the namespacing as long as it's `[something]/[original rest endpoint]`. Potentially also a way to unsubscribe, though that might be weird to have as a route, since that would mean you could allow an app to subscribe but forbid them from unsubscribing (maybe could be a GET/POST param for the same one instead).

So this way, just by controlling the path caveat, an app can have access to REST but not WS, or WS but not REST, or both (`"/(sub|api)/key/*"` as a permission), or neither. Since subscription to WS is done via a REST endpoint and not WS, the same macaroon/token passing system applies.

On subscribing, an event listener is registered somewhere to notify that container of new inputs. Containers still need to go through the WS handshake with proper auth (see #16) and this also identifies them to the store (kind of like a session cookie), so that the store knows which WS connections a subscribe request applies to.

So the advantages are:

- Permissions to access WS at all can be controlled separately (if it's at root, then with the path `"/"`, else `"/ws"` or `"/notif"` or something). We could even apply routes to WS connections for whatever purpose and have even more fine-grained control with the path caveat.
- All an app needs to do is open a WS connection as a client, then separately subscribe to stuff with normal requests. It would never actually have to send anything over WS to the store.
- All a driver needs to do is perform the WS handshake with their token on connection, then they can write normally without having to send over a token every time.
- Since subscription is by endpoint, path caveats apply, so no need to add additional complexity in checking permissions when a subscription request is made (though [that is certainly possible now](https://github.com/yousefamar/databox-store-blob/blob/5d66ea146b2fe08114db8dc32e1a7f95810af93c/src/lib/websockets/broadcastDataOverWebSocket.js#L11)) since you can just do it with paths.
- REST and WS for the same data have separate permissions, as they should.

If you guys think that's the way to go, I'd be happy to take a stab at it. I hope I explained that clearly enough, but let me know if something is unclear (I may have forgotten parts I was thinking of).

**Comment by Toshbrown** [comment]
This seems like a sensible course of action to me. The WS API is not being used yet so now would be a good time to get this done.
