### ISSUE TITLE
/cat endpoint should check for name collisions

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox-store-blob#21]
/cat endpoint should check for name collisions to stop drivers registering many things with one name.

**Comment by yousefamar** [comment]
The Hypercat specs say this about adding items with same name:

> 5.4.3 Where an item already exists in the catalogue, the
server shall replace the existing item with the new item
and respond with an HTTP 200 status code.

On that note, I think it might be good to modify the abstraction [`/cat/add`](https://github.com/me-box/databox-store-blob/blob/Hypercat/src/lib/hypercat/hypercat.js#L15) to straight up POST `/cat` with raw Hypercat items directly ([PAS section 5.4](http://shop.bsigroup.com/upload/276778/PAS_212.pdf)). This would mean drivers can interact with the store catalogue knowing nothing but pure Hypercat, and allow drivers to add custom metadata to store catalogues, which I think might be good for reasons discussed [here](https://github.com/me-box/admin/issues/3). If you think that's the way to go, I'd be happy to set it up.

Now that you brought this up, it made me think of some other issues on timing/order. Do we want to allow drivers to update store catalogues at any point run-time? E.g. a zillion years after a driver starts, suddenly it finds that there's another kind of stream of data it can get from it's source that wasn't available before, and then adds it to the store catalogue. Or one is now gone, so it wants to delete the item from the catalogue ([PAS section 5.6](http://shop.bsigroup.com/upload/276778/PAS_212.pdf)). My feeling is yes we do, but I'm not certain.

Either way, there would be a short period of time when a driver first starts where it's still populating its store catalogue, so ideally the catalogues would be walked anew every time you need that info for something (launching apps, searching app store, etc) and nothing is cached CM-side. Maybe even continuously crawling catalogues in the background and notifying the user of new items popping up as drivers are launched, find new stuff, and/or delete old stuff.

**Comment by Toshbrown** [comment]
> On that note, I think it might be good to modify the abstraction /cat/add to straight up POST /cat with raw Hypercat items directly (PAS section 5.4). This would mean drivers can interact with the store catalogue knowing nothing but pure Hypercat, and allow drivers to add custom metadata to store catalogues, which I think might be good for reasons discussed here. If you think that's the way to go, I'd be happy to set it up.

I think this is a good way forward. Happy for you to crack on with this then I can modify the drivers to match. 

>issues on timing/order. Do we want to allow drivers to update store catalogues at any point run-time?

I think drivers can update stores at any time, for example when a new device is discovered. However, apps only get access if the user explicitly binds that datasource to an App in the manifest to SLA conversion process. I don't think apps get access to the /cat endpoint on stores they just get told about what they have permission to use (to prevent leakage).  

There is probably some work to do in the CM UI to flag to users when a new datasource that an App can use becomes available. So they can reconfigure the app and permit access if desired.
