### ISSUE TITLE
Web sockets: sent data is not logged 

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox-store-blob#24]
The /sub and /unsub endpoints are logged. However, the data sent to Apps over the WS is not logged.

**Comment by yousefamar** [comment]
Does it need to be? Since `/write`s are being logged, and only data coming from `/write`s is being broadcast to subscribers, then by knowing who is subscribed to a stream, you also know what they get, right?

**Comment by Toshbrown** [comment]
We could do it that way but it makes the log queries a bit complex. Lets have a chat about it on the 15th

**Comment by haddadi** [comment]
agree, and extra logging worn't hurt.. as the "subscriber" might always go
away, so not be "present" in the DB lookup anymore, but they were given
data at some point historically


==
Hamed        http://www.eecs.qmul.ac.uk/~hamed/

**Comment by yousefamar** [comment]
Ok so if the only difference is optimisation, then we can just add this for simplicity and do optimisation later?

**Comment by Toshbrown** [comment]
Logging will be reimplemented in core-store. closing
