### ISSUE TITLE
Solve the data on-demand problem

### ISSUE THREAD

**Issue by yousefamar** [me-box/databox-store-blob#38]
I had a chat with @MMalekzadeh the other day when this came up. I think it's fundamental enough that it doesn't count as an early optimisation, so maybe should be tackled as soon as all the MVP things are done.

I'm not sure if this even is a problem right now, so any input is appreciated.

#### Problem ####
Certain kinds of drivers may expose a whole range of data sources. Certain apps may only need some of these. For the driver to be streaming all of these into a store at all times is inefficient, and uses up more resources than is necessary (source battery, bandwidth, disk space, etc).

For example, an app may only need a mobile phone's accelerometer data, so there's no reason it should be streaming microphone input to a store 24/7 too. (Or is there? Is making historical time series data — that existed before the birth of an app — available to that app allowed?)

#### Potential solutions ####
Some kinds of workarounds can already be done. For example, in a store where you want time series to only stream on-demand, you can have a small key-value store alongside it with a bunch of flags for each data source. Apps can set or unset these flags, a driver can read them, and start or stop requesting data from a source based on the value of these flags.

This becomes hard to manage though when you have more than one app that needs the same data sources since you would need to prevent one app from turning off the tap for another.

Another way may be to give drivers some way of finding out what apps have access to it's stores' data sources and which (e.g. arbiter endpoint?). That way, when an app is launched with permissions to read microphone data, the driver can start collecting that data, and when the last app with microphone permissions dies, the driver can stop.

**Comment by Toshbrown** [comment]
> (Or is there? Is making historical time series data — that existed before the birth of an app — available to that app allowed?)

It is my understanding that this is allowed. Storing historical data is one of the key aspects of the box. However, in your example, this could be problematic as the data stream is quite large and the device is not always on the local network. 

I wonder if there is a case for combining actuation with sensing to allow apps to turn certain sensors on and off? (not sure this is a good plan, security, contention, etc) 

It could also be down to driver configuration e.g, only log audio when the device is at home.

Another option would be a ring buffer store that only holds a set amount to data. Then apps could be written to process and compress the interesting parts of this for storage.

**Comment by yousefamar** [comment]
> I wonder if there is a case for combining actuation with sensing to allow apps to turn certain sensors on and off? (not sure this is a good plan, security, contention, etc)

I also think that might not be such a good idea. If we did need that, I think it would be better to switch sensors off at the driver level rather than the source device level.

> Another option would be a ring buffer store that only holds a set amount to data. Then apps could be written to process and compress the interesting parts of this for storage.

That's another interesting angle — longevity via derived stores. If you want more than just the last N seconds of audio, launch an app that writes to a second-order store that can afford to store more and even compress, that has the same type as the first, and can be substituted as the source store for an app.

That would at the same time be equivalent to splitting up the "mobile" store into individual stores for individual sources.

**Comment by yousefamar** [comment]
Closing in favour of https://github.com/me-box/databox/issues/9.
