### ISSUE TITLE
Https support

### ISSUE THREAD

**Issue by Toshbrown** [me-box/databox-store-blob#8]
APIs need moving to https with cert signed by the CM

**Comment by Toshbrown** [comment]
started in ade78e6529274fba06afc6e7cb9316f7955d3bb2

**Comment by yousefamar** [comment]
On this note, should the WebSocket part also be encrypted through TLS/SSL (and all `ws://` → `wss://`)? Not sure if that happens automatically when the server the `WebSocketServer` is on is HTTPS.

**Comment by Toshbrown** [comment]
>On this note, should the WebSocket part also be encrypted through TLS/SSL  

Yep and it think it is but it needs testing. 

see lines 57 to 78 of main.js

**Comment by Toshbrown** [comment]
Implemented ade78e6529274fba06afc6e7cb9316f7955d3bb2
